name: hourly
channels:
  - bioconda
  - conda-forge
  - defaults
  - gurobi
dependencies:
  - python
  - matplotlib
  - numpy
  - pandas
  - pypsa>=0.25.1
  - yaml
  - ca-certificates
  - certifi
  - openssl
  - pypdf2=1.28.4
  - pip
  - linopy
  - geopandas
  - seaborn
  - openpyxl
  - oyaml
  - snakemake
  - ipykernel
  - gurobi
  - pip:
    - vresutils
